project_id = "tkdxumnvptxqnqqlrhzr"

[functions.chat]
verify_jwt = false

[functions.handle-review-notification]
verify_jwt = false

[functions.send-review-email]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false